### ISSUE TITLE
Unexpected token export

### ISSUE THREAD

**Issue by Maysk** [zazuko/d3-sparql#11]
I am running on windows and having this error:
![image](https://user-images.githubusercontent.com/7331771/56701973-16066e00-66d8-11e9-9bfb-a6d10c0818bf.png)

Could anyone help me?

**Comment by l00mi** [comment]
What do you try to accomplish?

**Comment by Maysk** [comment]
I am sorry. I already solved it. I am kind of new using Node and Javascript and I hastened to create an issue here. I will try to be more careful. 

Thank you for your cooperation. :+1:
