### ISSUE TITLE
Allowing also POST requests.

### ISSUE THREAD

**Issue by l00mi** [zazuko/d3-sparql#2]
Currently only GET request can be issued which the majority of endpoints can handle. Some special use cases might still need POST requests.

**Comment by lucaswerkmeister** [comment]
> Some special use cases might still need POST requests.

For example, queries that are too long for GET can require POST. See [Gerrit change Ic3ea53c50e](https://gerrit.wikimedia.org/r/#/c/355131/) for how we implemented this in the Wikidata Query Service GUI.

**Comment by l00mi** [comment]
A nice, thank you for the pointer. We will definitely look into this.
Not sure yet though, if we want to go the *automatic retry* route.

**Comment by l00mi** [comment]
@lucaswerkmeister You got by any chance a too big query at hand?

**Comment by lucaswerkmeister** [comment]
Sure – the “co-author graph” of five authors on https://tools.wmflabs.org/scholia/authors/Q20980928,Q24290415,Q24390693,Q26720269,Q13520818 (embeds `query.wikidata.org`). If you look at the network requests in dev tools, you can see that it first tries GET and then falls back to POST.

**Comment by l00mi** [comment]
We can now do POST request. No automatic Upgrade is provided.
