### ISSUE TITLE
Consider wd-type-parser for data normalization

### ISSUE THREAD

**Issue by nyurik** [zazuko/d3-sparql#5]
A while back I wrote https://github.com/nyurik/wd-type-parser that might be useful for the Wikidata result normalization.  (includes extensive tests)

**Comment by l00mi** [comment]
That looks great. Point is that d3-sparql is not designed to exclusively query wikidata, but any SPARQL endpoint following the specs. So the [uri](https://github.com/nyurik/wd-type-parser/blob/master/src/wikidataTypeParser.js#L55) part is not really what we want here. Further compared to the [d3-sparql data nomalization](https://github.com/zazuko/d3-sparql/blob/master/src/sparql.js#L35) we are missing the datetime?

But if you don't mind I would love to copy some of your tests over?

**Comment by l00mi** [comment]
I also like the [wkt](https://github.com/nyurik/wd-type-parser/blob/master/src/wikidataTypeParser.js#L46) part, I have to check how d3 expects that kind of variables.

**Comment by nyurik** [comment]
Hmm, the date is a special beast... i'm worried that it might not convert cleanly in some cases...

**Comment by nyurik** [comment]
Tests - sure, you are welcome to copy them. Make sure to follow the license though (MIT :D )

**Comment by nyurik** [comment]
Sorry, I meant it as a joke.  MIT basically means - do (almost) whatever, just don't blame me :)  But a link to original source is always nice ;)
