### ISSUE TITLE
Can't get the examples to work

### ISSUE THREAD

**Issue by zawsx** [zazuko/d3-sparql#6]
Am using localhost. 
Get the following error when running /examples/minimal.html :
Uncaught TypeError: d3Request.request is not a function
    at Object.sparql (d3-sparql.js:26)
    at minimal.html:21
This is the line giving the error:
 var sparql = d3Request.request(url).mimeType('application/sparql-results+json').response(response);
d3Request seems to be a valid object.

Same happens with /examples/timeline.html
Can't figure out why - apologies if it's a newbie error :)

**Comment by l00mi** [comment]
For the examples to work you need the d3 packages.

Run `npm install` in the directory.

**Comment by zawsx** [comment]
Thanks for the response, appreciated :)
I did install the packages (otherwise there would have been a different error)  - worked fine.
Can see that the D3 scripts are being directly loaded from node_modules. 

I looked at the code and it all looks fine to me - can't see why the 'not a function' error comes up d3Request 
clearly is one. Stuck!

p.s. BTW I noticed that D3 request is deprecated in favour of D3 fetch (am thinking to update when I go the examples to work) not that that matters at this stage.

**Comment by l00mi** [comment]
Ah okay, please be aware that this library still depends on D3 Version 3!

**Comment by zawsx** [comment]
Thanks again for your kindness. It works now. I lazily assumed that the "pretest" script in package.json was not relevant to me wanting to just run the examples, being more used to seeing a "start" script if one is needed. 

I'm on Windows so the rm of the build dir of that script doesn't work. Like a fool I thought I could run the rollup after the install completes in case it was somehow needed for the examples but clearly I cannot. IOW I think it's because rollup wasn't run during install rather than after it.  If so, in the pre-test script a W10-compatible version of
rm -rf build
would cure it I guess. I just re-downloaded the source, removed the rm -rf build and hey presto, it works on install.
__________________
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> d3-sparql@1.0.0 prepublish C:\Users\w10\Documents\dev\sz.tld\utils\sparQL
> npm run test && uglifyjs build/d3-sparql.js -c -m -o build/d3-sparql.min.js

> d3-sparql@1.0.0 pretest C:\Users\w10\Documents\dev\sz.tld\utils\sparQL
> mkdir build && rollup -g d3-request:d3 -f umd -n d3 -o build/d3-sparql.js -- index.js

> d3-sparql@1.0.0 test C:\Users\w10\Documents\dev\sz.tld\utils\sparQL
> tape 'test/**/*-test.js'

added 68 packages from 94 contributors in 2.795s
> node -v
v9.2.0
> npm -v
5.8.0
__________________________________
BTW in case it helps, I noticed a range of examples of what your code will do nicely here:
https://github.com/ktym/d3sparql
__________________________________
I append my package-lock.json for completeness:
{
  "name": "d3-sparql",
  "version": "1.0.0",
  "lockfileVersion": 1,
  "requires": true,
  "dependencies": {
    "align-text": {
      "version": "0.1.4",
      "resolved": "https://registry.npmjs.org/align-text/-/align-text-0.1.4.tgz",
      "integrity": "sha1-DNkKVhCT810KmSVsIrcGlDP60Rc=",
      "dev": true,
      "requires": {
        "kind-of": "3.2.2",
        "longest": "1.0.1",
        "repeat-string": "1.6.1"
      }
    },
    "ansi-regex": {
      "version": "2.1.1",
      "resolved": "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz",
      "integrity": "sha1-w7M6te42DYbg5ijwRorn7yfWVN8=",
      "dev": true
    },
    "ansi-styles": {
      "version": "2.2.1",
      "resolved": "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz",
      "integrity": "sha1-tDLdM1i2NM914eRmQ2gkBTPB3b4=",
      "dev": true
    },
    "balanced-match": {
      "version": "1.0.0",
      "resolved": "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz",
      "integrity": "sha1-ibTRmasr7kneFk6gK4nORi1xt2c=",
      "dev": true
    },
    "brace-expansion": {
      "version": "1.1.8",
      "resolved": "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.8.tgz",
      "integrity": "sha1-wHshHHyVLsH479Uad+8NHTmQopI=",
      "dev": true,
      "requires": {
        "balanced-match": "1.0.0",
        "concat-map": "0.0.1"
      }
    },
    "camelcase": {
      "version": "1.2.1",
      "resolved": "https://registry.npmjs.org/camelcase/-/camelcase-1.2.1.tgz",
      "integrity": "sha1-m7UwTS4LVmmLLHWLCKPqqdqlijk=",
      "dev": true
    },
    "center-align": {
      "version": "0.1.3",
      "resolved": "https://registry.npmjs.org/center-align/-/center-align-0.1.3.tgz",
      "integrity": "sha1-qg0yYptu6XIgBBHL1EYckHvCt60=",
      "dev": true,
      "requires": {
        "align-text": "0.1.4",
        "lazy-cache": "1.0.4"
      }
    },
    "chalk": {
      "version": "1.1.3",
      "resolved": "https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz",
      "integrity": "sha1-qBFcVeSnAv5NFQq9OHKCKn4J/Jg=",
      "dev": true,
      "requires": {
        "ansi-styles": "2.2.1",
        "escape-string-regexp": "1.0.5",
        "has-ansi": "2.0.0",
        "strip-ansi": "3.0.1",
        "supports-color": "2.0.0"
      }
    },
    "cliui": {
      "version": "2.1.0",
      "resolved": "https://registry.npmjs.org/cliui/-/cliui-2.1.0.tgz",
      "integrity": "sha1-S0dXYP+AJkx2LDoXGQMukcf+oNE=",
      "dev": true,
      "requires": {
        "center-align": "0.1.3",
        "right-align": "0.1.3",
        "wordwrap": "0.0.2"
      }
    },
    "commander": {
      "version": "2.11.0",
      "resolved": "https://registry.npmjs.org/commander/-/commander-2.11.0.tgz",
      "integrity": "sha512-b0553uYA5YAEGgyYIGYROzKQ7X5RAqedkfjiZxwi0kL1g3bOaBNNZfYkzt/CL0umgD5wc9Jec2FbB98CjkMRvQ=="
    },
    "concat-map": {
      "version": "0.0.1",
      "resolved": "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz",
      "integrity": "sha1-2Klr13/Wjfd5OnMDajug1UBdR3s=",
      "dev": true
    },
    "d3-collection": {
      "version": "1.0.4",
      "resolved": "https://registry.npmjs.org/d3-collection/-/d3-collection-1.0.4.tgz",
      "integrity": "sha1-NC39EoN8kJdPM/HMCnha6lcNzcI="
    },
    "d3-dispatch": {
      "version": "1.0.3",
      "resolved": "https://registry.npmjs.org/d3-dispatch/-/d3-dispatch-1.0.3.tgz",
      "integrity": "sha1-RuFJHqqbWMNY/OW+TovtYm54cfg="
    },
    "d3-dsv": {
      "version": "1.0.5",
      "resolved": "https://registry.npmjs.org/d3-dsv/-/d3-dsv-1.0.5.tgz",
      "integrity": "sha1-QZ99tH9ih4n8P9tjbmeESdCCETY=",
      "requires": {
        "commander": "2.11.0",
        "iconv-lite": "0.4.18",
        "rw": "1.3.3"
      }
    },
    "d3-request": {
      "version": "1.0.5",
      "resolved": "https://registry.npmjs.org/d3-request/-/d3-request-1.0.5.tgz",
      "integrity": "sha1-TarpRtHdDVff4B8CKVY1SVjVHyM=",
      "requires": {
        "d3-collection": "1.0.4",
        "d3-dispatch": "1.0.3",
        "d3-dsv": "1.0.5",
        "xmlhttprequest": "1.8.0"
      }
    },
    "decamelize": {
      "version": "1.2.0",
      "resolved": "https://registry.npmjs.org/decamelize/-/decamelize-1.2.0.tgz",
      "integrity": "sha1-9lNNFRSCabIDUue+4m9QH5oZEpA=",
      "dev": true
    },
    "deep-equal": {
      "version": "1.0.1",
      "resolved": "https://registry.npmjs.org/deep-equal/-/deep-equal-1.0.1.tgz",
      "integrity": "sha1-9dJgKStmDghO/0zbyfCK0yR0SLU=",
      "dev": true
    },
    "define-properties": {
      "version": "1.1.2",
      "resolved": "https://registry.npmjs.org/define-properties/-/define-properties-1.1.2.tgz",
      "integrity": "sha1-g6c/L+pWmJj7c3GTyPhzyvbUXJQ=",
      "dev": true,
      "requires": {
        "foreach": "2.0.5",
        "object-keys": "1.0.11"
      }
    },
    "defined": {
      "version": "1.0.0",
      "resolved": "https://registry.npmjs.org/defined/-/defined-1.0.0.tgz",
      "integrity": "sha1-yY2bzvdWdBiOEQlpFRGZ45sfppM=",
      "dev": true
    },
    "es-abstract": {
      "version": "1.7.0",
      "resolved": "https://registry.npmjs.org/es-abstract/-/es-abstract-1.7.0.tgz",
      "integrity": "sha1-363ndOAb/Nl/lhgCmMRJyGI/uUw=",
      "dev": true,
      "requires": {
        "es-to-primitive": "1.1.1",
        "function-bind": "1.1.0",
        "is-callable": "1.1.3",
        "is-regex": "1.0.4"
      }
    },
    "es-to-primitive": {
      "version": "1.1.1",
      "resolved": "https://registry.npmjs.org/es-to-primitive/-/es-to-primitive-1.1.1.tgz",
      "integrity": "sha1-RTVSSKiJeQNLZ5Lhm7gfK3l13Q0=",
      "dev": true,
      "requires": {
        "is-callable": "1.1.3",
        "is-date-object": "1.0.1",
        "is-symbol": "1.0.1"
      }
    },
    "escape-string-regexp": {
      "version": "1.0.5",
      "resolved": "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz",
      "integrity": "sha1-G2HAViGQqN/2rjuyzwIAyhMLhtQ=",
      "dev": true
    },
    "for-each": {
      "version": "0.3.2",
      "resolved": "https://registry.npmjs.org/for-each/-/for-each-0.3.2.tgz",
      "integrity": "sha1-LEBFC5NI6X8oEyJZO6lnBLmr1NQ=",
      "dev": true,
      "requires": {
        "is-function": "1.0.1"
      }
    },
    "foreach": {
      "version": "2.0.5",
      "resolved": "https://registry.npmjs.org/foreach/-/foreach-2.0.5.tgz",
      "integrity": "sha1-C+4AUBiusmDQo6865ljdATbsG5k=",
      "dev": true
    },
    "fs.realpath": {
      "version": "1.0.0",
      "resolved": "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz",
      "integrity": "sha1-FQStJSMVjKpA20onh8sBQRmU6k8=",
      "dev": true
    },
    "function-bind": {
      "version": "1.1.0",
      "resolved": "https://registry.npmjs.org/function-bind/-/function-bind-1.1.0.tgz",
      "integrity": "sha1-FhdnFMgBeY5Ojyz391KUZ7tKV3E=",
      "dev": true
    },
    "glob": {
      "version": "7.1.2",
      "resolved": "https://registry.npmjs.org/glob/-/glob-7.1.2.tgz",
      "integrity": "sha512-MJTUg1kjuLeQCJ+ccE4Vpa6kKVXkPYJ2mOCQyUuKLcLQsdrMCpBPUi8qVE6+YuaJkozeA9NusTAw3hLr8Xe5EQ==",
      "dev": true,
      "requires": {
        "fs.realpath": "1.0.0",
        "inflight": "1.0.6",
        "inherits": "2.0.3",
        "minimatch": "3.0.4",
        "once": "1.4.0",
        "path-is-absolute": "1.0.1"
      }
    },
    "has": {
      "version": "1.0.1",
      "resolved": "https://registry.npmjs.org/has/-/has-1.0.1.tgz",
      "integrity": "sha1-hGFzP1OLCDfJNh45qauelwTcLyg=",
      "dev": true,
      "requires": {
        "function-bind": "1.1.0"
      }
    },
    "has-ansi": {
      "version": "2.0.0",
      "resolved": "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz",
      "integrity": "sha1-NPUEnOHs3ysGSa8+8k5F7TVBbZE=",
      "dev": true,
      "requires": {
        "ansi-regex": "2.1.1"
      }
    },
    "iconv-lite": {
      "version": "0.4.18",
      "resolved": "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.18.tgz",
      "integrity": "sha512-sr1ZQph3UwHTR0XftSbK85OvBbxe/abLGzEnPENCQwmHf7sck8Oyu4ob3LgBxWWxRoM+QszeUyl7jbqapu2TqA=="
    },
    "inflight": {
      "version": "1.0.6",
      "resolved": "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz",
      "integrity": "sha1-Sb1jMdfQLQwJvJEKEHW6gWW1bfk=",
      "dev": true,
      "requires": {
        "once": "1.4.0",
        "wrappy": "1.0.2"
      }
    },
    "inherits": {
      "version": "2.0.3",
      "resolved": "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz",
      "integrity": "sha1-Yzwsg+PaQqUC9SRmAiSA9CCCYd4=",
      "dev": true
    },
    "is-buffer": {
      "version": "1.1.5",
      "resolved": "https://registry.npmjs.org/is-buffer/-/is-buffer-1.1.5.tgz",
      "integrity": "sha1-Hzsm72E7IUuIy8ojzGwB2Hlh7sw=",
      "dev": true
    },
    "is-callable": {
      "version": "1.1.3",
      "resolved": "https://registry.npmjs.org/is-callable/-/is-callable-1.1.3.tgz",
      "integrity": "sha1-hut1OSgF3cM69xySoO7fdO52BLI=",
      "dev": true
    },
    "is-date-object": {
      "version": "1.0.1",
      "resolved": "https://registry.npmjs.org/is-date-object/-/is-date-object-1.0.1.tgz",
      "integrity": "sha1-mqIOtq7rv/d/vTPnTKAbM1gdOhY=",
      "dev": true
    },
    "is-function": {
      "version": "1.0.1",
      "resolved": "https://registry.npmjs.org/is-function/-/is-function-1.0.1.tgz",
      "integrity": "sha1-Es+5i2W1fdPRk6MSH19uL0N2ArU=",
      "dev": true
    },
    "is-regex": {
      "version": "1.0.4",
      "resolved": "https://registry.npmjs.org/is-regex/-/is-regex-1.0.4.tgz",
      "integrity": "sha1-VRdIm1RwkbCTDglWVM7SXul+lJE=",
      "dev": true,
      "requires": {
        "has": "1.0.1"
      }
    },
    "is-symbol": {
      "version": "1.0.1",
      "resolved": "https://registry.npmjs.org/is-symbol/-/is-symbol-1.0.1.tgz",
      "integrity": "sha1-PMWfAAJRlLarLjjbrmaJJWtmBXI=",
      "dev": true
    },
    "kind-of": {
      "version": "3.2.2",
      "resolved": "https://registry.npmjs.org/kind-of/-/kind-of-3.2.2.tgz",
      "integrity": "sha1-MeohpzS6ubuw8yRm2JOupR5KPGQ=",
      "dev": true,
      "requires": {
        "is-buffer": "1.1.5"
      }
    },
    "lazy-cache": {
      "version": "1.0.4",
      "resolved": "https://registry.npmjs.org/lazy-cache/-/lazy-cache-1.0.4.tgz",
      "integrity": "sha1-odePw6UEdMuAhF07O24dpJpEbo4=",
      "dev": true
    },
    "longest": {
      "version": "1.0.1",
      "resolved": "https://registry.npmjs.org/longest/-/longest-1.0.1.tgz",
      "integrity": "sha1-MKCy2jj3N3DoKUoNIuZiXtd9AJc=",
      "dev": true
    },
    "minimatch": {
      "version": "3.0.4",
      "resolved": "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz",
      "integrity": "sha512-yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==",
      "dev": true,
      "requires": {
        "brace-expansion": "1.1.8"
      }
    },
    "minimist": {
      "version": "1.2.0",
      "resolved": "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz",
      "integrity": "sha1-o1AIsg9BOD7sH7kU9M1d95omQoQ=",
      "dev": true
    },
    "object-inspect": {
      "version": "1.2.2",
      "resolved": "https://registry.npmjs.org/object-inspect/-/object-inspect-1.2.2.tgz",
      "integrity": "sha1-yCEV5PzIiK6hTWTCLk8X9qcNXlo=",
      "dev": true
    },
    "object-keys": {
      "version": "1.0.11",
      "resolved": "https://registry.npmjs.org/object-keys/-/object-keys-1.0.11.tgz",
      "integrity": "sha1-xUYBd4rVYPEULODgG8yotW0TQm0=",
      "dev": true
    },
    "once": {
      "version": "1.4.0",
      "resolved": "https://registry.npmjs.org/once/-/once-1.4.0.tgz",
      "integrity": "sha1-WDsap3WWHUsROsF9nFC6753Xa9E=",
      "dev": true,
      "requires": {
        "wrappy": "1.0.2"
      }
    },
    "path-is-absolute": {
      "version": "1.0.1",
      "resolved": "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz",
      "integrity": "sha1-F0uSaHNVNP+8es5r9TpanhtcX18=",
      "dev": true
    },
    "path-parse": {
      "version": "1.0.5",
      "resolved": "https://registry.npmjs.org/path-parse/-/path-parse-1.0.5.tgz",
      "integrity": "sha1-PBrfhx6pzWyUMbbqK9dKD/BVxME=",
      "dev": true
    },
    "repeat-string": {
      "version": "1.6.1",
      "resolved": "https://registry.npmjs.org/repeat-string/-/repeat-string-1.6.1.tgz",
      "integrity": "sha1-jcrkcOHIirwtYA//Sndihtp15jc=",
      "dev": true
    },
    "resolve": {
      "version": "1.3.3",
      "resolved": "https://registry.npmjs.org/resolve/-/resolve-1.3.3.tgz",
      "integrity": "sha1-ZVkHw0aahoDcLeOidaj91paR8OU=",
      "dev": true,
      "requires": {
        "path-parse": "1.0.5"
      }
    },
    "resumer": {
      "version": "0.0.0",
      "resolved": "https://registry.npmjs.org/resumer/-/resumer-0.0.0.tgz",
      "integrity": "sha1-8ej0YeQGS6Oegq883CqMiT0HZ1k=",
      "dev": true,
      "requires": {
        "through": "2.3.8"
      }
    },
    "right-align": {
      "version": "0.1.3",
      "resolved": "https://registry.npmjs.org/right-align/-/right-align-0.1.3.tgz",
      "integrity": "sha1-YTObci/mo1FWiSENJOFMlhSGE+8=",
      "dev": true,
      "requires": {
        "align-text": "0.1.4"
      }
    },
    "rollup": {
      "version": "0.27.1",
      "resolved": "https://registry.npmjs.org/rollup/-/rollup-0.27.1.tgz",
      "integrity": "sha1-c5kxsHhM8AwnS5US0shS5CBVolc=",
      "dev": true,
      "requires": {
        "chalk": "1.1.3",
        "minimist": "1.2.0",
        "source-map-support": "0.4.15"
      }
    },
    "rw": {
      "version": "1.3.3",
      "resolved": "https://registry.npmjs.org/rw/-/rw-1.3.3.tgz",
      "integrity": "sha1-P4Yt+pGrdmsUiF700BEkv9oHT7Q="
    },
    "source-map": {
      "version": "0.5.6",
      "resolved": "https://registry.npmjs.org/source-map/-/source-map-0.5.6.tgz",
      "integrity": "sha1-dc449SvwczxafwwRjYEzSiu19BI=",
      "dev": true
    },
    "source-map-support": {
      "version": "0.4.15",
      "resolved": "https://registry.npmjs.org/source-map-support/-/source-map-support-0.4.15.tgz",
      "integrity": "sha1-AyAt9lwG0r2MfsI2KhkwVv7407E=",
      "dev": true,
      "requires": {
        "source-map": "0.5.6"
      }
    },
    "string.prototype.trim": {
      "version": "1.1.2",
      "resolved": "https://registry.npmjs.org/string.prototype.trim/-/string.prototype.trim-1.1.2.tgz",
      "integrity": "sha1-0E3iyJ4Tf019IG8Ia17S+ua+jOo=",
      "dev": true,
      "requires": {
        "define-properties": "1.1.2",
        "es-abstract": "1.7.0",
        "function-bind": "1.1.0"
      }
    },
    "strip-ansi": {
      "version": "3.0.1",
      "resolved": "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz",
      "integrity": "sha1-ajhfuIU9lS1f8F0Oiq+UJ43GPc8=",
      "dev": true,
      "requires": {
        "ansi-regex": "2.1.1"
      }
    },
    "supports-color": {
      "version": "2.0.0",
      "resolved": "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz",
      "integrity": "sha1-U10EXOa2Nj+kARcIRimZXp3zJMc=",
      "dev": true
    },
    "tape": {
      "version": "4.7.0",
      "resolved": "https://registry.npmjs.org/tape/-/tape-4.7.0.tgz",
      "integrity": "sha512-ePzu2KfZYVtq0v+KKGxBJ9HJWYZ4MaQWeGabD+KpVdMKRen3NJPf6EiwA5BxfMkhQPGtCwnOFWelcB39bhOUng==",
      "dev": true,
      "requires": {
        "deep-equal": "1.0.1",
        "defined": "1.0.0",
        "for-each": "0.3.2",
        "function-bind": "1.1.0",
        "glob": "7.1.2",
        "has": "1.0.1",
        "inherits": "2.0.3",
        "minimist": "1.2.0",
        "object-inspect": "1.2.2",
        "resolve": "1.3.3",
        "resumer": "0.0.0",
        "string.prototype.trim": "1.1.2",
        "through": "2.3.8"
      }
    },
    "through": {
      "version": "2.3.8",
      "resolved": "https://registry.npmjs.org/through/-/through-2.3.8.tgz",
      "integrity": "sha1-DdTJ/6q8NXlgsbckEV1+Doai4fU=",
      "dev": true
    },
    "uglify-js": {
      "version": "2.8.29",
      "resolved": "https://registry.npmjs.org/uglify-js/-/uglify-js-2.8.29.tgz",
      "integrity": "sha1-KcVzMUgFe7Th913zW3qcty5qWd0=",
      "dev": true,
      "requires": {
        "source-map": "0.5.6",
        "uglify-to-browserify": "1.0.2",
        "yargs": "3.10.0"
      }
    },
    "uglify-to-browserify": {
      "version": "1.0.2",
      "resolved": "https://registry.npmjs.org/uglify-to-browserify/-/uglify-to-browserify-1.0.2.tgz",
      "integrity": "sha1-bgkk1r2mta/jSeOabWMoUKD4grc=",
      "dev": true,
      "optional": true
    },
    "window-size": {
      "version": "0.1.0",
      "resolved": "https://registry.npmjs.org/window-size/-/window-size-0.1.0.tgz",
      "integrity": "sha1-VDjNLqk7IC76Ohn+iIeu58lPnJ0=",
      "dev": true
    },
    "wordwrap": {
      "version": "0.0.2",
      "resolved": "https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.2.tgz",
      "integrity": "sha1-t5Zpu0LstAn4PVg8rVLKF+qhZD8=",
      "dev": true
    },
    "wrappy": {
      "version": "1.0.2",
      "resolved": "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz",
      "integrity": "sha1-tSQ9jz7BqjXxNkYFvA0QNuMKtp8=",
      "dev": true
    },
    "xmlhttprequest": {
      "version": "1.8.0",
      "resolved": "https://registry.npmjs.org/xmlhttprequest/-/xmlhttprequest-1.8.0.tgz",
      "integrity": "sha1-Z/4HXFwk/vOfnWX197f+dRcZaPw="
    },
    "yargs": {
      "version": "3.10.0",
      "resolved": "https://registry.npmjs.org/yargs/-/yargs-3.10.0.tgz",
      "integrity": "sha1-9+572FfdfB0tOMDnTvvWgdFDH9E=",
      "dev": true,
      "requires": {
        "camelcase": "1.2.1",
        "cliui": "2.1.0",
        "decamelize": "1.2.0",
        "window-size": "0.1.0"
      }
    }
  }
}
_________________________________
Thanks again for your patience but most of all, thanks for the code! If I can improve it, I will.

**Comment by l00mi** [comment]
Thank you! We hopefully will find some time to improve stuff in summer. Meanwhile happy to see PRs!

**Comment by l00mi** [comment]
Can you test if this now works out of the box on windows too? https://github.com/zazuko/d3-sparql/commit/1d4abb7c4106c4dbe068812f6c47c8743d3e6849
Thanks

**Comment by zawsx** [comment]
Works perfectly, thanks!
_______________
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> d3-sparql@1.0.0 prepublish C:\Users\w10\Documents\dev\sz.tld\utils\d3-sparql
> npm run test && uglifyjs build/d3-sparql.js -c -m -o build/d3-sparql.min.js


> d3-sparql@1.0.0 pretest C:\Users\w10\Documents\dev\sz.tld\utils\d3-sparql
> rimraf build && mkdirp build && rollup -g d3-request:d3 -f umd -n d3 -o build/d3-sparql.js -- index.js


> d3-sparql@1.0.0 test C:\Users\w10\Documents\dev\sz.tld\utils\d3-sparql
> tape 'test/**/*-test.js'

added 71 packages from 94 contributors in 3.4s
